#
# Available repositories are listed here:
# https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
#

sudo: false

language:
  - cpp

addons:
  apt:
    packages:
    - g++
    - gdb
    - libqt4-dev
    - libqt4-opengl-dev

#env:
#- COMPILER_VERSION=4.6

before_script:
  - gcc --version
  - mkdir build-debug
  - cd build-debug
  - qmake-qt4 ../nbody.pro CONFIG+=debug CONFIG+=build-gcov
  - cd ..

script:
  - cd build-debug
  - make -j2
  - export LD_LIBRARY_PATH=./nbody:${LD_LIBRARY_PATH}
  - ./test/engine/engine
  - ./test/solver/solver
  - cd nbody
  - gcov ./*

after_success:
  - bash <(curl -s https://codecov.io/bash)
