#
# Available repositories are listed here:
# https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
#

sudo: false

language:
  - cpp

addons:
  apt:
    packages:
    - g++
    - libqt4-dev
    - libqt4-opengl-dev

#env:
#- COMPILER_VERSION=4.6

before_script:
  - gcc --version
  - mkdir build-debug
  - cd build-debug
  - qmake-qt4 ../nbody/nbody.pro CONFIG+=debug
  - cd ..

script:
  - cd build-debug
  - make -j2
