#
# Available repositories are listed here:
# https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
#

sudo: required
dist: trusty

language:
  - cpp

addons:
  apt:
    packages:
    - g++
    - gdb
    - valgrind
    - libqt4-dev
    - libqt4-opengl-dev

#env:
#- COMPILER_VERSION=4.6

before_script:
  - gcc --version
  - mkdir build-debug-gcov
  - mkdir build-debug-valg
  - cd build-debug-gcov
  - qmake-qt4 ../nbody.pro CONFIG+=debug CONFIG+=build-gcov
  - cd ..
  - cd build-debug-valg
  - qmake-qt4 ../nbody.pro CONFIG+=debug
  - cd ..

script:
  - export LD_LIBRARY_PATH=./nbody:${LD_LIBRARY_PATH}
  - cd build-debug-valg
  - make -j2
  - valgrind --tool=memcheck --trace-children=yes --log-file=./memsupp.log --gen-suppressions=all --smc-check=all --read-var-info=yes --leak-check=full --track-origins=yes ./test/memsupp/memsupp
  - grep -v "==" ./memsupp.log | sed 's/_ZN12test_memsuppC1Ev/\*/g'> ./valg.supp
#  - valgrind --tool=memcheck --error-exitcode=1 --trace-children=yes --suppressions=./valg.supp --smc-check=all --read-var-info=yes --leak-check=full --track-origins=yes ./test/engine/engine
  - valgrind --tool=memcheck --error-exitcode=1 --trace-children=yes --suppressions=./valg.supp --smc-check=all --read-var-info=yes --leak-check=full --track-origins=yes ./test/solver/solver
  - cd ..
  - cd build-debug-gcov
  - make -j2
  - ./test/engine/engine
  - ./test/solver/solver
  - ./test/solvers_equality/solvers_equality
  - cd nbody
  - gcov ./*

after_success:
  - bash <(curl -s https://codecov.io/bash)
